version: '3.8'

networks:
    external_network:
        external: true
        name: ${DEFAULT_DOCKER_NETWORK}

services:

    scheduler:
        user: root
        image: ${SCHEDULER_IMAGE}
        hostname: ${CONTAINER_NAME_PREFIX}_scheduler
        container_name: ${CONTAINER_NAME_PREFIX}_scheduler
        env_file:
            - ${DOCKER_PHP_APP_PATH}/.env
            - ${DOCKER_PHP_SCHEDULER_PATH}/.env
        volumes:
            - ${DOCKER_PHP_PATH}/docker-entrypoint.sh:/entrypoint.sh:ro
            - ${ROOT_PATH}:/var/www/app:delegated
        ports:
            - ${DOCKER_PHP_SCHEDULER_PORT:-8011}:8080
        networks:
            external_network:
        logging:
            driver: "json-file"
            options:
                max-size: "1m"
                max-file: "5"
                mode: "non-blocking"
                tag: "logging-scheduler"
