---
version: '3.8'

networks:
    external_network:
        external: true
        name: ${DEFAULT_DOCKER_NETWORK}

volumes:
    minio_data:

services:

    minio:
        image: quay.io/minio/minio
        hostname: minio
        container_name: ${CONTAINER_NAME_PREFIX}_minio
        ports:
            - ${DOCKER_MINIO_API_PORT:-9000}:9000
            - ${DOCKER_MINIO_CONSOLE_PORT:-9001}:9001
        volumes:
            - minio_data:/data
        environment:
            - MINIO_ROOT_USER=${DOCKER_MINIO_ROOT_USER:-root}
            - MINIO_ROOT_PASSWORD=${DOCKER_MINIO_ROOT_PASSWORD:-minioadmin}
        command: server /data --console-address ":${DOCKER_MINIO_CONSOLE_PORT:-9001}"
        networks:
            external_network:
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:${DOCKER_MINIO_API_PORT:-9000}/minio/health/live"]
            start_period: 5s
            interval: 30s
            timeout: 5s
            retries: 3
